/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package homework3;

import org.junit.jupiter.api.Test;


import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;


class AppTest {

    App app = new App();

    @Test
    void testEmptyArray() {//gonderilen liste bos ise false don
        ArrayList<Car> cars = new ArrayList<>();
        assertFalse(app.cancelCar(cars, 2, "toyota", true));
    }

    @Test
    void testProductFound() { // arac listede varsa true don
        ArrayList<Car> cars = carList();
        assertTrue(app.cancelCar(cars, 4, "toyota", true));
    }

    @Test
    void testCarNotFound() {  // arac listede yoksa false don
        ArrayList<Car> cars = carList();
        assertFalse(app.cancelCar(cars, 4, "fiat", true));
    }

    @Test
    void testProductCancellationConfirmed() { //aracin silinmesi onaylanmissa true don
        ArrayList<Car> cars = carList();
        assertTrue(app.cancelCar(cars, 4, "toyota", true));
    }

    @Test
    void testCarCancellationNotConfirmed() { //aracin silinmesi onaylanmamissa false don
        ArrayList<Car> cars = carList();
        assertFalse(app.cancelCar(cars, 1, "toyota", false));
    }

 


    public ArrayList<Car> carList() {
        Car car1 = new Car("toyota", 5);
        Car car2 = new Car("mercedes", 3);
        Car car3 = new Car("bmw", 1);
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(car1);
        cars.add(car2);
        cars.add(car3);
        return cars;
    }
}