// /*
//  * This Java source file was generated by the Gradle 'init' task.
//  */
// package homework3;

// import org.junit.jupiter.api.Test;


// import static org.junit.jupiter.api.Assertions.*;

// import java.util.ArrayList;
// import java.util.Arrays;

// class AppTest {

//     App app = new App();

//     @Test
//     void testEmptyArray() {//gönderilen dizi boş ise false dön
//         ArrayList<Car> cars = new ArrayList<>();
//         assertFalse(app.cancelCar(cars, 2, "saat", true));
//     }

//     @Test
//     void testProductFound() { // Ürün listede varsa true dön
//         ArrayList<Car> cars = carList();
//         assertTrue(app.cancelCar(cars, 4, "saat", true));
//     }

//     @Test
//     void testCarNotFound() {  // Ürün listede yoksa false dön
//         ArrayList<Car> cars = carList();
//         assertFalse(app.cancelCar(cars, 4, "table", true));
//     }

//     @Test
//     void testProductCancellationConfirmed() { //Ürün silmesine onay verilmisse true dön
//         ArrayList<Car> cars = carList();
//         assertTrue(app.cancelCar(cars, 4, "saat", true));
//     }

//     @Test
//     void testCarCancellationNotConfirmed() { //Ürün silmesine onay verilmemisse false dön
//         ArrayList<Car> cars = carList();
//         assertFalse(app.cancelCar(cars, 1, "telefon", false));
//     }

//     @Test
//     void testCarCountValid() {  //ürün listesinden silinen ürünün girilen miktardan çok veya eşit ise true dön
//         ArrayList<Car> cars = carList();
//         assertTrue(app.cancelCar(cars, 1, "telefon", true));
//     }

//     @Test
//     void testCarCountNotValid() { //ürün listesinden silinen ürünün girilen miktardan az ise false dön
//         ArrayList<Car> cars = carList();
//         assertFalse(app.cancelCar(cars, 4, "telefon", true));
//     }


//     public ArrayList<Car> carList() {
//         Car car1 = new Car("saat", 5);
//         Car car2 = new Car("telefon", 3);
//         Car car3 = new Car("bilgisayar", 1);
//         ArrayList<Car> cars = new ArrayList<>();
//         cars.add(car1);
//         cars.add(car2);
//         cars.add(car3);
//         return cars;
//     }
// }